# Objetivos

## Objetivo Geral

  Partindo de tudo o que foi discutido acima, é possível desenhar o que viria a ser o objetivo desta pesquisa. Qual seja, _entender se o processo de Conversão Religiosa e/ou contato com a Religiosidade/Espiritualidade durante o tratamento influenciou na Recuperação e Manutenção da abstêmia de indivíduos que já deram entrada em Comunidades Terapêuticas Religiosas_. A pesquisa será quantitativa e a nível nacional, podendo participar homens e mulheres que tenham dado entrada ou concluído o tratamento para uso abusivo de drogas em uma Comunidade Terapêutica.

## Objetivos Específicos

1. Entender como os egressos de Comunidades Terapêuticas avaliam a importância da Conversão Religiosa dentro do contexto do Programa Terapêutico e fora dele. 
2. Avaliar se, nos dados coletados, existe alguma relação sólida entre a manutenção da abstêmia e ser convertido ao credo da CT.
3. Avaliar se, nos dados coletados, existe alguma relação sólida entre a recuperação do uso abusivo de drogas e ser convertido ao credo da CT. 
4. Observar, através de levantamentos bibliográficos e documentais, as controvérsias percebidas nos discursos sobre Comunidades Terapêuticas emitidas por atores nos níveis micro e macrossocial. 
5. Observar através de levantamentos bibliográficos e documentais quais são atores mobilizados nas discussões.
6. Entender, no contexto dos dados coletados, qual seria a implicância da introdução de espiritualidade e religiosidade no itinerário do tratamento.

\newpage