# Hipóteses

Baseado no que foi debatido duas hipóteses são levantadas e, com a ajuda dos dados coletados, serão testadas.

## **H1**: _“Religiosidade pode corroborar na saúde físico/mental dos sujeitos pesquisados e na sensação de recuperação.”_

  É demonstrado em vários estudos que cultivar algum credo religioso tende a trazer uma série de benefícios, tais como facilidade na recuperação de doenças [@cerqueira-santos_religiao_2004-1], em especial as de cunho mental [@krause_stress_2011], criação e manutenção de hábitos ditos saudáveis [@verona_explanations_2011], melhorias na vida financeira [@mariz_libertacao_1994; @potter_growth_2016] etc. Para além desses, também é possível encontrar estudos que apontam a conversão ou a simples adesão à religiões cristãs enquanto uma das formas de enfrentamento da dependência, como os vícios em álcool e substâncias psicotrópicas em geral [@mariz_libertacao_1994; @rocha_o_2012-1; @smilde_qualitative_2005; @targino_os_2016-1]. 
  
  Ao se observar as pesquisas relacionadas a CT’s percebe-se que a Religiosidade e a Conversão Religiosa são encaradas, tanto por egressos quanto indivíduos em tratamento, como um dos motivadores pessoais para permanência no tratamento [@chu_religious_2012,206 ; @shields_religion_2007, 367], assim como auxiliam no empoderamento pessoal do sujeito e na transformação identitária e comportamental [@targino_comunidades_2017-1,327]. Especificamente em pesquisas com egressos de CT’s percebe-se que ser convertido a algum credo, em especial judaico-cristão, é um dos motivos pelos quais eles mantêm o estado de abstêmia. Segundo Vaglum [-@vaglum_why_1985,351] ter tido experiências religiosas ou ser convertido foi um fator crucial para 10% dos egressos pesquisados.  
  
  Tais evidências demonstram que a Conversão geralmente tende a ter algumas características positivas para quem dela vivencia e costuma trazer consigo uma série de benefícios que podem auxiliar o indivíduo em sua jornada. Logo, neste trabalho pretende-se encontrar nos dados uma perspectiva similar na qual a Conversão em si ou a simples adesão produziram alguns efeitos positivos no que diz respeito a sensação de recuperação.

## **H2**: _“A Conversão Religiosa não será uma condição presente em todas as configurações possíveis que expliquem a Abstêmia ou a Recuperação”_

  Apesar de reconhecer que a Conversão Religiosa, assim como a simples filiação, possuem alguns benefícios positivos para o indivíduo, não se acredita que ela será uma variável importante para explicar **todos** os casos no qual o egresso se manteve abstêmico. Isso se sustenta pelo simples fato de que não existe uma única forma de se alcançar um resultado. A essa característica damos o nome de _multicausalidade_, um fenômeno comum nos objetos de pesquisa das Ciências Sociais [@schneider_set-theoretic_2012]. 

  Na pesquisa com egressos de Vaglum [-@vaglum_why_1985] aponta que, para 71% dos egressos, a vontade própria era o que figurava como elemento motivador do estado de abstinência, outros fatores situacionais, como um novo relacionamento, melhorar a relação com os pais ou começar a trabalhar tiveram maior impacto que fatores religiosos [@vaglum_why_1985, 351]. Shields et al [-@shields_religion_2007,367] destaca que a religiosidade individual não tem impacto sobre o nível de retenção (estadia) do tratamento, mas apenas sobre o cometimento individual com o proposto pelo programa. Scaduto, Barbieri e Santos [-@scaduto_comunidades_2014, 167] apontam que todos os resultados encontrados em seu estudo sobre egressos de CT’s variaram segundo o nível de dano sofrido no período de drogadição e características da própria personalidade e não por características do modelo empregado pela CT. Tais informações além de demonstrarem que o efeito da religião é difuso, também apontam o quão frágil e perigoso é confiar todos os casos de uso abusivo de drogas a modelos exclusivamente abstêmios, como prenuncia o Capítulo II da Lei 13.840 de 5 de junho de 2019.  

  A partir destas pressuposições assume-se que, nas configurações que geraram como resultado a abstêmia, algumas não contaram com a presença da Conversão Religiosa. Outras condições demonstraram um poder explicativo maior.


## **H3**: _“A Conversão Religiosa não se apresentará como uma condição necessária ou suficiente para a explicação geral da Abstêmia ou Recuperação”_ 

  Tendo como base a hipótese anterior, de que a Conversão Religiosa não conseguirá ser parte da explicação causal de todos as configurações que tenham como resultado a abstêmia, assume-se que ela não poderá ser um fator necessário para a existência da mesma, e muito menos suficiente em si mesmo para a explicação do resultado. A única pesquisa encontrada que vai no oposto do aqui proposto é a de Perrone [-@perrone_fatores_2019] na qual se afirma haver correlação inversamente proporcional entre participação de grupos religiosos e chances de recidiva [@perrone_fatores_2019,142]. Tal efeito, no entanto, se mostra como não pertencente a Religião em si dado que as próprias variáveis que mensuram elementos religiosos (Religião e Prática Religiosa) deram resultados não significativos. As redes sociais providas é que se provaram como mais eficazes de explicação da não recidiva. 
  
  Redes sociais são também um fator essencial na própria Conversão dos indivíduos. Um exemplo disso é o estudo de Smilde [-@smilde_qualitative_2005] sobre motivação para Conversão entre Venezuelanos. Apesar de, discursivamente, os principais motivos elencados para a Conversão Religiosa fossem “querer mudar de vida” ou “se livrar das drogas” análises de QCA (Qualitative Comparative Analysis) apontaram que era conviver com protestantes, e não a resolução de problemas, o fator necessário, suficiente e significativo para causar a Conversão naquele grupo [@smilde_qualitative_2005, 766]. Estudos de outras áreas também apontam sobre o efeito das redes sociais no próprio processo de recuperação do uso abusivo de drogas [@costa2001processo]. Estudos como esses servem de indicativo para sempre prestar um olhar crítico e parcimonioso sobre elementos que discursivamente podem parecer ter efeito, mas que, sob análise acurada, podem não o ter.
  
  Acredita-se, por fim, que outras condições e configurações terão uma consistência maior do que o simples fato de se Converter quando o resultado for a manutenção da abstêmia, logo tal variável não será suficiente, muito menos necessária, para o outcome positivo


\newpage