# Conclusão

  Em guisa de conclusão, percebe-se que, na medida do possível, os objetivos colocados por esta pesquisa foram alcançados. Apesar dos encalços e das problemáticas com a natureza da pesquisa e da população estudada conseguiu-se com êxito entender suas jornadas e avaliar de forma efetiva os efeitos das práticas de Conversão Religiosa na Abstêmia/Recuperação.
  
  Constatou-se que em nenhuma das fórmulas causais encontradas pela QCA a Conversão teve papel ativo ou positivo, ao contrário, foi a sua ausência que proporcionou com que ambos os outcomes estudados, Abstêmia e Percepção de Recuperação, acontecessem. Para além disso os dados coletados também comprovam que a Conversão, diferente da narrativa vendida pelas instituições que defendem as CT's, é uma prática comum e incentivada no _milieu_ terapêutico. 
  
  A presente pesquisa também conseguiu traçar uma gênese dessas instituições no Brasil, tendo como ponto de partida seus encontros e desencontros com instâncias público governamentais e privadas. Conseguiu-se ainda traçar sua conexão direta com outras instituições religiosas e entender, em parte, como o projeto das CT's e o dos religiosos no poder são duas faces da mesma moeda.
  
  Recomenda-se, enfim, a elaboração de mais pesquisas, seja no campo das metodologias configuracionais, seja no campo quantitativo convencional, que levem em consideração efeitos a longo prazo das práticas terapêuticas utilizadas por essas instituições que crescem em poder e quantidade no solo nacional. Se faz necessário ultrapassar a barreira do apoio exclusivo do discurso que as metologias qualitativas construíram e começar a coletar outros tipos de evidência que possam comprovar ou contestar a narrativa que as CT's vem construindo de si e do seu trabalho.
